name: Lint

on:
  push:
    branches: "*"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - run: npm install -g npm@latest

      - run: npm install

      - name: ESLint
        run: npm run lint
