name: Playwright Tests

on:
  - push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      with:
        run_install: true

    - name: Install Playwright Browsers
      run: pnpm playwright install --with-deps

    - name: Build for Chrome
      run: pnpm build:chrome

    - name: Run Playwright tests
      run: xvfb-run -- pnpm playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
