name: Type Check

on:
  push:
    branches: "*"

jobs:
  type-check:
    name: Typescript Compiler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - run: npm install -g npm@latest

      - run: npm install

      - name: Run Typescript Compiler
        run: npm run type-check
